version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install
          command: |
            yarn
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Deploy
          command: |
            yarn deploy

